#!/usr/bin/env python3
"""
Build-time converter: dashboard.html → photo_web_pages.h

Wraps HTML in a C++ raw string literal so the browser dashboard
can be edited as a standalone .html file with full IDE support.
"""
import sys, os

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <dashboard.html> <photo_web_pages.h>")
        sys.exit(1)

    html_path = sys.argv[1]
    header_path = sys.argv[2]

    with open(html_path, 'r', encoding='utf-8') as f:
        html = f.read()

    # Pick a raw-string delimiter that doesn't appear in the HTML
    for delim in ['END===="', 'DONE="', 'XXX="', 'EOF="']:
        if delim not in html:
            break
    else:
        print("ERROR: HTML contains all candidate delimiters")
        sys.exit(1)

    header = f'''#pragma once

// AUTO-GENERATED by html_to_header.py — DO NOT EDIT
// Edit dashboard.html instead
static const char *WEB_INDEX_HTML = R"{delim}(
{html}
){delim}";
'''

    # Write only if changed (avoids triggering recompilation)
    if os.path.exists(header_path):
        with open(header_path, 'r', encoding='utf-8') as f:
            old = f.read()
        if old == header:
            return  # unchanged, skip

    with open(header_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header)
    print(f"Generated: {header_path} ({len(html)} bytes HTML)")

if __name__ == '__main__':
    main()
